"""empty message

Revision ID: c536213306e8
Revises: c2574e16e814
Create Date: 2023-01-31 15:25:26.620430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c536213306e8'
down_revision = 'c2574e16e814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
